import { BadRequestException, Injectable } from '@nestjs/common';
import { InjectConnection } from '@nestjs/sequelize';
import { Sequelize } from 'sequelize-typescript';
import * as XLSX from 'xlsx';

@Injectable()
export class ExcelImportService {
  constructor(
    @InjectConnection() private readonly sequelize: Sequelize,
  ) { }

  /**
   * Helper function to clean a string key (lowercase, no spaces, hyphens, or underscores)
   * for flexible column matching.
   */
  private cleanKey(key: string): string {
    return key.toLowerCase().replace(/[\s_-]/g, '');
  }

  async importExcel(file: Express.Multer.File, modelName: string) {
    if (!file) {
      throw new BadRequestException('No file uploaded.');
    }
    if (!modelName) {
      throw new BadRequestException('Model name is required.');
    }

    // Retrieve the Sequelize Model dynamically and flexibly (case-insensitive, ignores spaces/underscores)
    let ModelClass = this.sequelize.models[modelName];
    if (!ModelClass) {
      const cleanedTargetName = this.cleanKey(modelName);
      const matchedKey = Object.keys(this.sequelize.models).find(key => {
        const cleanedKey = this.cleanKey(key);
        const modelTable = this.cleanKey((this.sequelize.models[key] as any).tableName || '');
        return cleanedKey === cleanedTargetName || modelTable === cleanedTargetName;
      });
      if (matchedKey) {
        ModelClass = this.sequelize.models[matchedKey];
      }
    }

    if (!ModelClass) {
      const availableModels = Object.keys(this.sequelize.models).join(', ');
      throw new BadRequestException(
        `Model with name "${modelName}" not found in Sequelize registry. Available models: ${availableModels}`
      );
    }

    try {
      // Read Excel sheet buffer
      const workbook = XLSX.read(file.buffer, { type: 'buffer' });
      const sheetName = workbook.SheetNames[0];
      const sheet = workbook.Sheets[sheetName];

      // Convert sheet rows to JSON
      const rawRows = XLSX.utils.sheet_to_json(sheet);
      if (!rawRows || rawRows.length === 0) {
        throw new BadRequestException('Excel sheet is empty.');
      }

      // Get attributes of the model
      const modelAttributes = Object.keys(ModelClass.getAttributes());
      const cleanedAttributesMap = new Map<string, string>();
      for (const attr of modelAttributes) {
        cleanedAttributesMap.set(this.cleanKey(attr), attr);
      }

      // Map raw rows to model fields, skipping rows that don't match any fields or are empty
      const recordsToInsert = rawRows
        .map((row: any) => {
          const record: any = {};
          let hasAnyField = false;
          for (const rawKey of Object.keys(row)) {
            const cleanedKey = this.cleanKey(rawKey);
            const matchedAttr = cleanedAttributesMap.get(cleanedKey);
            if (matchedAttr) {
              let val = row[rawKey];
              
              // Normalize string representations of null/undefined
              if (typeof val === 'string') {
                const trimmed = val.trim().toLowerCase();
                if (trimmed === 'null' || trimmed === 'undefined') {
                  val = null;
                }
              }

              // Handle auto-generated key columns
              const isAutoGenerated = ['id', 'createdat', 'updatedat'].includes(matchedAttr.toLowerCase());
              if (isAutoGenerated && (val === undefined || val === null || val === '')) {
                // Skip so Sequelize/database defaults are triggered
              } else {
                record[matchedAttr] = (val === '') ? null : val;
                hasAnyField = true;
              }
            }
          }
          return hasAnyField ? record : null;
        })
        .filter((record) => record !== null);

      if (recordsToInsert.length === 0) {
        const parsedKeys = Object.keys(rawRows[0] || {});
        throw new BadRequestException(
          `No valid columns matched or file contains only empty rows. Your Excel headers: [${parsedKeys.join(', ')}]. ` +
          `Expected columns matching these model attributes: [${modelAttributes.join(', ')}] (case-insensitive, ignoring spaces/underscores).`
        );
      }

      // Insert records inside a single transaction
      const result = await this.sequelize.transaction(async (transaction) => {
        return await ModelClass.bulkCreate(recordsToInsert, {
          validate: true, // run model validations
          transaction,
        });
      });

      return {
        success: true,
        message: `Successfully imported ${result.length} records into ${modelName}.`,
        count: result.length,
      };
    } catch (error: any) {
      console.error('Excel Import Error Details:', error);
      
      let errMsg = error.message || String(error);
      
      // Extract specific Sequelize validation details
      if (error.name === 'SequelizeValidationError' && error.errors) {
        errMsg = error.errors.map((e: any) => `${e.path}: ${e.message}`).join(' | ');
      } else if (error.name === 'SequelizeUniqueConstraintError' && error.errors) {
        errMsg = error.errors.map((e: any) => `${e.path} must be unique: ${e.message}`).join(' | ');
      }
      
      throw new BadRequestException(`Import failed: ${errMsg}`);
    }
  }
}
