export const FIELD_KIND_TEXT = 'text';
export const FIELD_KIND_EMPLOYEE_REF = 'employee_ref';
export const FIELD_KIND_ROLE_REF = 'role_ref';

export const DEPARTMENT_TABLE_CODE = 'department';

export const ALLOWED_CUSTOM_FIELD_KINDS = [FIELD_KIND_TEXT, FIELD_KIND_EMPLOYEE_REF, FIELD_KIND_ROLE_REF] as const;
export type CustomFieldKind = (typeof ALLOWED_CUSTOM_FIELD_KINDS)[number];

export const MAX_CUSTOM_COLUMNS = 50;
export const TEXT_MAX_LENGTH = 255;

/** Lowercase identifiers blocked for text column codes and employee column name slugs. */
export const RESERVED_COLUMN_CODES = new Set([
  // System / ORM columns (departments)
  'id',
  'name',
  'code',
  'is_active',
  'createdat',
  'updatedat',
  'created_at',
  'updated_at',
  'deletedat',
  'deleted_at',
  'default_hod_employee_id',
  'default_coordinator_employee_id',

  // PostgreSQL reserved keywords
  'all',
  'analyse',
  'analyze',
  'and',
  'any',
  'array',
  'as',
  'asc',
  'asymmetric',
  'authorization',
  'binary',
  'both',
  'case',
  'cast',
  'check',
  'collate',
  'column',
  'constraint',
  'create',
  'cross',
  'current_catalog',
  'current_date',
  'current_role',
  'current_time',
  'current_timestamp',
  'current_user',
  'default',
  'deferrable',
  'desc',
  'distinct',
  'do',
  'else',
  'end',
  'except',
  'false',
  'fetch',
  'for',
  'foreign',
  'from',
  'grant',
  'group',
  'having',
  'in',
  'initially',
  'intersect',
  'into',
  'lateral',
  'leading',
  'limit',
  'localtime',
  'localtimestamp',
  'not',
  'null',
  'offset',
  'on',
  'only',
  'or',
  'order',
  'placing',
  'primary',
  'references',
  'returning',
  'select',
  'session_user',
  'some',
  'symmetric',
  'table',
  'then',
  'to',
  'trailing',
  'true',
  'union',
  'unique',
  'user',
  'using',
  'variadic',
  'when',
  'where',
  'window',
  'with',

  // SQL DDL / DML / administration
  'add',
  'alter',
  'begin',
  'by',
  'call',
  'cascade',
  'commit',
  'copy',
  'database',
  'delete',
  'drop',
  'exec',
  'execute',
  'explain',
  'filter',
  'flush',
  'function',
  'if',
  'index',
  'insert',
  'join',
  'key',
  'left',
  'like',
  'lock',
  'merge',
  'modify',
  'natural',
  'new',
  'no',
  'old',
  'outer',
  'over',
  'partition',
  'procedure',
  'public',
  'read',
  'rename',
  'replace',
  'restrict',
  'revoke',
  'right',
  'rollback',
  'row',
  'rows',
  'savepoint',
  'schema',
  'set',
  'show',
  'start',
  'system',
  'temp',
  'temporary',
  'transaction',
  'trigger',
  'truncate',
  'unnest',
  'update',
  'values',
  'view',
  'write',
  'zone',
]);

export const COLUMN_CODE_REGEX = /^[A-Z][A-Z0-9_]{1,62}$/;

export const EMPLOYEE_COLUMN_CODE_REGEX = /^default_[a-z][a-z0-9_]*_employee_id$/;

export const EMPLOYEE_REFERENCE_TABLE = 'employee_details';
export const ROLE_REFERENCE_TABLE = 'roles';

export const ROLE_COLUMN_CODE_REGEX = /^default_[a-z][a-z0-9_]*_role_id$/;
