export const CONTACT_SUPPORT_BY_ROLE = {
  student: {
    pageClass: 'student-page contact-support-page',
    headerClass: 'page-header',
    title: 'Contact Support',
    subtitle: 'Need help? Our support team is here to assist you with any questions or issues.',
    initialFormData: {
      fullName: 'Arjun Kapoor',
      email: 'bruce.wayne@university.edu',
      subject: '',
      category: '',
      message: '',
    },
    subjectOptions: [
      { value: 'technical', label: 'Technical Issue' },
      { value: 'academic', label: 'Academic Query' },
      { value: 'other', label: 'Other' },
    ],
    categoryOptions: [
      { value: 'portal', label: 'Portal Access' },
      { value: 'grievance', label: 'Grievance Submission' },
      { value: 'account', label: 'Account Settings' },
    ],
    faqPath: '/student/faq',
  },
  admin: {
    pageClass: 'admin-overview-page contact-support-page',
    headerClass: 'page-header',
    title: 'IT & Developer Support',
    subtitle: 'Technical assistance for system administrators and portal managers.',
    initialFormData: {
      fullName: 'System Admin',
      email: 'admin@university.edu',
      subject: '',
      category: '',
      message: '',
    },
    subjectOptions: [
      { value: 'bug', label: 'System Bug / Error' },
      { value: 'data', label: 'Data Export/Import' },
      { value: 'access', label: 'Role & Access Management' },
      { value: 'other', label: 'Other Technical Query' },
    ],
    categoryOptions: [
      { value: 'dashboard', label: 'Analytics Dashboard' },
      { value: 'routing', label: 'Grievance Routing' },
      { value: 'users', label: 'User Management' },
      { value: 'notifications', label: 'Email/SMS Gateway' },
    ],
    faqPath: '/admin/faq',
  },
  hod: {
    pageClass: 'hod-dashboard contact-support-page',
    headerClass: 'page-header-alt',
    title: 'Contact Support',
    subtitle: 'Need technical assistance? Our admin support team is here to help you manage the portal effectively.',
    initialFormData: {
      fullName: 'Rajiv Mehta',
      email: 'hod@gmail.com',
      subject: '',
      category: '',
      message: '',
    },
    subjectOptions: [
      { value: 'technical', label: 'Portal Bug / Error' },
      { value: 'access', label: 'Access Control Issue' },
      { value: 'reporting', label: 'Report Generation Error' },
      { value: 'other', label: 'Other Technical Query' },
    ],
    categoryOptions: [
      { value: 'dashboard', label: 'Dashboard Metrics' },
      { value: 'workflow', label: 'Grievance Workflow' },
      { value: 'account', label: 'Admin Account Settings' },
    ],
    faqPath: '/staff/faq',
  },
  staff: {
    pageClass: 'hod-dashboard contact-support-page',
    headerClass: 'page-header-alt',
    title: 'Contact Support',
    subtitle: 'Need technical assistance? Our admin support team is here to help you manage the portal effectively.',
    initialFormData: {
      fullName: '',
      email: '',
      subject: '',
      category: '',
      message: '',
    },
    subjectOptions: [
      { value: 'technical', label: 'Portal Bug / Error' },
      { value: 'access', label: 'Access Control Issue' },
      { value: 'reporting', label: 'Report Generation Error' },
      { value: 'other', label: 'Other Technical Query' },
    ],
    categoryOptions: [
      { value: 'dashboard', label: 'Dashboard Metrics' },
      { value: 'workflow', label: 'Grievance Workflow' },
      { value: 'account', label: 'Account Settings' },
    ],
    faqPath: '/staff/faq',
  },
};
